version: '3'

services:
  gradio_app:
    image: python:3.11
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "python gradio_app.py"
    env_file:
      - .env
    environment:
      - TZ=America/Bogota
    ports:
      - 7860:7860